import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — ChatGPT.cheap",
  description: "Terms of Service for ChatGPT.cheap.",
};

const LAST_UPDATED = "April 2026";

export default function TermsPage() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p className="text-sm">Last updated: {LAST_UPDATED}</p>

      <h2>1. Acceptance</h2>
      <p>
        By using ChatGPT.cheap ("the Service") you agree to these Terms. If you do not agree, do not
        use the Service.
      </p>

      <h2>2. Account</h2>
      <p>
        You are responsible for safeguarding access to your email inbox, since authentication is via
        magic link. You agree to provide accurate information during signup.
      </p>

      <h2>3. Plans and billing</h2>
      <ul>
        <li>Subscriptions are billed monthly in advance via Stripe.</li>
        <li>
          We support three tiers: Starter ($9/mo), Growth ($19/mo), Pro ($29/mo). Tier capabilities
          are listed at /pricing.
        </li>
        <li>
          You can cancel anytime — your plan stays active until the end of the current billing
          period.
        </li>
        <li>
          Prices may change. Existing subscribers keep current pricing for at least 90 days after a
          change is announced.
        </li>
      </ul>

      <h2>4. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Submit prompts that violate the acceptable-use policies of OpenAI or Google.</li>
        <li>Use the Service to harass, defame, or impersonate any person or brand.</li>
        <li>Attempt to reverse-engineer, scrape, or overload the Service.</li>
        <li>Resell raw AI provider outputs obtained via the Service.</li>
      </ul>
      <p>We may suspend or terminate accounts that violate this policy.</p>

      <h2>5. Content ownership</h2>
      <p>
        You own the brand data and query prompts you submit. The raw provider responses are
        generated by third parties (OpenAI, Google). The mention analysis, structured metadata, and
        dashboard views derived from those responses are made available to you as part of your
        subscription.
      </p>

      <h2>6. Service availability</h2>
      <p>
        We aim for high availability but do not guarantee uninterrupted service. Scheduled
        maintenance will be announced in advance when possible. We do not offer formal SLAs on the
        standard plans.
      </p>

      <h2>7. Disclaimers</h2>
      <p>
        The Service is provided "as is". AI providers may change their outputs or pricing at any
        time, which may affect the data you see. We do not guarantee completeness or accuracy of
        AI-generated content.
      </p>

      <h2>8. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, our aggregate liability for any claim arising from
        the Service is limited to the amount you paid us in the 12 months preceding the claim.
      </p>

      <h2>9. Termination</h2>
      <p>
        You may cancel at any time via the Customer Portal. We may terminate or suspend access for
        violation of these Terms.
      </p>

      <h2>10. Governing law</h2>
      <p>
        These Terms are governed by the laws of the jurisdiction where the operator is registered.
        Disputes will be resolved in the courts of that jurisdiction.
      </p>

      <h2>11. Contact</h2>
      <p>support@chatgpt.cheap</p>
    </>
  );
}
